// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_zX0l4mjfvsKm-LEesfcJFi8Ya-DwsM',
    appId: '1:615688490530:web:f44634fc7928928ff5447b',
    messagingSenderId: '615688490530',
    projectId: 'test-tut1-5593d',
    authDomain: 'test-tut1-5593d.firebaseapp.com',
    storageBucket: 'test-tut1-5593d.firebasestorage.app',
    measurementId: 'G-FLLD8W2QQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQsoLs7rsvYAfog4ifa5gUGuFFTBZ-jw',
    appId: '1:615688490530:android:f137a2a4e2c73bfef5447b',
    messagingSenderId: '615688490530',
    projectId: 'test-tut1-5593d',
    storageBucket: 'test-tut1-5593d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrIB1wdmj338S0KGBc7uADTN6RQdkzvM',
    appId: '1:615688490530:ios:83864aa7586c22b8f5447b',
    messagingSenderId: '615688490530',
    projectId: 'test-tut1-5593d',
    storageBucket: 'test-tut1-5593d.firebasestorage.app',
    iosBundleId: 'com.example.recap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxrIB1wdmj338S0KGBc7uADTN6RQdkzvM',
    appId: '1:615688490530:ios:83864aa7586c22b8f5447b',
    messagingSenderId: '615688490530',
    projectId: 'test-tut1-5593d',
    storageBucket: 'test-tut1-5593d.firebasestorage.app',
    iosBundleId: 'com.example.recap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ_zX0l4mjfvsKm-LEesfcJFi8Ya-DwsM',
    appId: '1:615688490530:web:1c6adc9469b3236ff5447b',
    messagingSenderId: '615688490530',
    projectId: 'test-tut1-5593d',
    authDomain: 'test-tut1-5593d.firebaseapp.com',
    storageBucket: 'test-tut1-5593d.firebasestorage.app',
    measurementId: 'G-90HLPJ730J',
  );
}
